### ISSUE TITLE
e gặp vấn đề ip table

### ISSUE THREAD

**Issue by tamvvvv** [juhonkang/robot_auto_planning#1]
![CentOS 6 - VMware Workstation 5_22_2024 10_35_24 AM](https://github.com/juhonkang/robot_auto_planning/assets/169439746/370055ee-ebb0-4ccb-b679-e57c5cdf480d)
![CentOS 6 - VMware Workstation 5_22_2024 10_37_53 AM](https://github.com/juhonkang/robot_auto_planning/assets/169439746/cf7e82ce-08d2-49e6-b548-f868840c927e)
![Windows 10 - VMware Workstation 5_22_2024 10_43_44 AM](https://github.com/juhonkang/robot_auto_planning/assets/169439746/dcd9c448-89d1-474a-9287-0c73347e8682)
dạ a ơi e ko ping đc ba máy này e phải cài ntn vậy anh

**Comment by juhonkang** [comment]
@tamsayshit k add trực tiếp vào một repo bất kì e nhé

**Comment by tamvvvv** [comment]
dạ là sao vậy anh?
